name: Build

on:
  push:
    branches:
      - main
    tags-ignore:
      - '**'
  pull_request:
    branches:
      - main

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: npm
          cache-dependency-path: package-lock.json
      - name: Install dependencies
        run: npm ci
      - name: Check coding style
        run: npm run lint
      - name: Build
        run: npm run build
      - name: Check changes
        id: check-changes
        if: github.event_name == 'push'
        run: |
          git add --all docs
          if git diff-index --name-status --exit-code HEAD docs; then
            echo 'No changes detected.'
          else
            echo 'Changes detected.'
            echo 'commit=yes' >> $GITHUB_OUTPUT
          fi
      - name: Commit changes
        if: steps.check-changes.outputs.commit == 'yes'
        run: |
          git config --local user.name 'GitHub Actions'
          git config --local user.email noreply@github.com
          git add --all docs
          git commit -m 'Update docs'
          git push
      - name: Setup Pages
        if: steps.check-changes.outputs.commit == 'yes'
        uses: actions/configure-pages@v5
      - name: Upload artifact
        if: steps.check-changes.outputs.commit == 'yes'
        uses: actions/upload-pages-artifact@v3
        with:
          path: docs
      - name: Deploy to GitHub Pages
        if: steps.check-changes.outputs.commit == 'yes'
        id: deployment
        uses: actions/deploy-pages@v4
